spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db url}
    username: ${db username}
    password: ${db password}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
OPENVIDU_URL: ${openvidu url}
OPENVIDU_SECRET: SINABRO
 
server:
  port: 5000
  ssl:
    enabled: false
    
# 파일 저장 경로 배포할 때는 리눅스에 맞춰 변경해주자
file:
  path: /var/ubuntu/sinabro/files/
